// OBJECTS CAN BE PARSED AND SORTED BY KEY ONLINE HERE: http://www.jsoneditoronline.org/
var auto_correct = {
"9090": "90-90 Test (hamstrings length): *** degrees R, *** degrees L (normal 70 degrees or >)",
"1ktc": "single knee to chest",
"1on1": "The hi-volt electric stimulation treatment this encounter required one-on-one constant attendance because: A) It was the first e-stim treatment using this waveform making it necessary for  the therapist and patient to work together in real-time to optimize electrode placement and intensity settings, B) There is a history of hyper-irritability in the area(s) being treated and  the one-on-one attendance was necessary to reassure to the patient, both A+B)",
"1rm": "1 repetition maximum",
"1x10": "1 set of 10 repetitions",
"2d": "secondary to",
"2hourrule": "2 hour rule, a.k.a. your *** may be uncomfortable for an hour or two after exercising or engaging in activities, but if the pain goes on for hours and hours after the exercise/activity, then that level of activity is probably too much (at this time).",
"2ktc": "two knees to chest",
"2manpb": "2 person back-to-back standing plyoball 1) pass with trunk rotation then 2) pass with trunk rotation then thrust in front. Verbal cues to engage abdominal muscles.",
"2mansb": "2 person – standing/facing – 4 hands on physioball for dynamic abdominal strengthening doing 1) chest press to 2) ball overhead to 3) up/right to 4) up/left to 5) squat. Verbal cues to engage abdominal muscles.",
"2person": "2 person physioball 'Around the World' with cues to engage abdominal muscles, wide stance leaning forward with 4 hands on the ball, going A) chest and up, B) chest and up to right, C) chest and up to left",
"2weekrule": "my advice about return to sport is let a week go by during which you are essentially pain-free, and then wait another full week",
"2x10": "2 sets of 10 repetitions",
"2x23": "2-3 repetitions hold 20-30 seconds each, 2-3 x daily",
"3and9": "3 o'clock and 9 o'clock",
"3x10": "3 sets of 10 repetitions",
"4key": "4 key principles: (1. keep loads close to your center of gravity, 2. maintain lumbar lordosis and lift with your legs not your back, 3. Engage abdominals to lend support to your low back when it is under a load, and 4. Don't twist and lift)",
"4sq": "4 Square Drills - A) frontwards/backwards ***x, B) left-right-left ***x, C) clockwise ***x",
"4stair": "stairs agility drills, facing up, up-down 1, up-down 2, etc.to up-down 4 with *** railing(s)",
"5tstst": "5 times sit to stand *** sec",
"6and12": "6 o'clock and 12 o'clock",
"6mwt": "6 minute walk test",
"12foam": "1/2 foam roller",
"23x": "2-3 repetitions hold 20-30 seconds each, 2-3 x daily",
"55cm": "55 cm (red) physioball",
"65cm": "65 cm (blue) physioball",
"105d": "105 degrees of knee flexion is typically enough to perform well at rising from chairs/toilets, getting in/out of small cars, going up/down stairs step-over-step, etc.",
"aad": "ambulatory assistive device",
"aarom": "active-assisted ROM",
"abm": "applied body mechanics",
"abmi": "applied body mechanics instruction",
"abmrx": "applied body mechanics instruction",
"abx": "anti-biotics",
"acj": "acromio-clavicular joint",
"adl": "activities of daily living",
"af01": "supine isometric ankle plantarflexion w/ pillow (af-01)",
"af02": "supine isometric ankle dorsiflexion w/ pillow (af-02)",
"af03": "supine isometric ankle eversion w/ pillow (af-03)",
"af04": "supine isometric ankle inversion w/ pillow (af-04)",
"af05": "seated ankle dorsiflexion resisted ROM w/ elastic (af-05)",
"af06": "seated ankle plantarflexion resisted ROM w/ elastic (af-06)",
"af07": "seated ankle inversion resisted ROM w/ elastic (af-07)",
"af08": "seated ankle eversion resisted ROM w/ elastic (af-08)",
"af09": "seated ankle alphabets active ROM (af-09)",
"af10": "seated single leg toe curling active ROM w/ towel (af-10)",
"af11": "seated double leg toe curling active ROM w/ towel (af-11)",
"af12": "standing on step/stool, plantar fascia and calf stretch (af-12)",
"af13": "standing soleus muscle closed kinetic chain stretch (af-13)",
"af14": "standing gastrocnemius muscle closed kinetic chain stretch (af-14)",
"af15": "standing one foot balance (af-15)",
"af16": "seated ankle circles active ROM (af-16)",
"af17": "supine leg elevated ankle pumps active ROM (af-17)",
"af18": "supine ankle pump active ROM (af-18)",
"af19": "supine ankle inversion/eversion active ROM (af-19)",
"af20": "standing bilateral heel rise active ROM (af-20)",
"af21": "standing unilateral heel rise active ROM (af-21)",
"af22": "standing toe raise active ROM (af-22)",
"af23": "seated heel raise active ROM (af-23)",
"af24": "seated toe raise active ROM (af-24)",
"af25": "seated toes - pick up objects active ROM (af-25)",
"af26": "standing foam balance (af-26)",
"af27": "seated ankle dorsiflexion resisted ROM w/ cuff weight (af-27)",
"af28": "prone ankle plantarflexion resisted ROM w/ knee flexed w/ cuff weight (af-28)",
"af29": "sidelying ankle inversion resisted ROM w/ cuff weight (af-29)",
"af30": "sidelying ankle eversion resisted ROM w/ cuff weight (af-30)",
"af31": "seated toe curling active ROM (af-31)",
"af32": "seated ankle plantarflexion/dorsiflexion passive ROM (af-32)",
"af33": "seated ankle inversion/eversion passive ROM (af-33)",
"af34": "seated toe flexion/extension passive ROM (af-34)",
"af35": "standing le diagonal D1 flexion resisted ROM with elastic (af-35)",
"af36": "standing le diagonal D1 extension resisted ROM with elastic (af-36)",
"af37": "standing le diagonal D2 flexion resisted ROM with elastic (af-37)",
"af38": "standing le diagonal D2 extension resisted ROMwith elastic (af-38)",
"agil1": "Agility drills w/ rope rectangle/circle: in-in-out-out side to side",
"agil2": "Agility drills w/ rope rectangle/circle: in-in-out-out forward and back - leading w/ right, repeat leading w/ left",
"agil3": "Agility drills w/ rope rectangle/circle: 'Heisman' - in-in-out/in-in-out (side step and 'stick' the landing)",
"agil4": "Agility drills w/ rope rectangle/circle: apart and together - leading w/ right, repeat leading w/ left",
"ao3": "alert and oriented x 3",
"aodm": "adult onset diabetes mellitus",
"aqpt": "aquatic physical therapy",
"aral": "alternating right and left",
"arom": "active ROM",
"asis": "anterior superior iliac spine",
"athetosis": "no athetosis, tremor, rigidity, or dystonia",
"athetosisabsent": "no athetosis, tremor, rigidity, or dystonia",
"avs": "after visit summary",
"b55": "55 cm (red) physioball",
"b65": "65 cm (blue) physioball",
"baps": "Biomechanical Ankle Platform System (BAPS) board",
"bc": "because",
"bil": "bilateral",
"bily": "bilaterally",
"bk01": "prone press up on elbows passive ROM (bk-01)",
"bk02": "prone full press up passive ROM (bk-02)",
"bk03": "prone upper back extension active ROM (bk-03)",
"bk04": "prone hip extension active ROM (bk-04)",
"bk05": "prone alternate arm and leg lift active ROM (bk-05)",
"bk06": "standing wall lean stretch (bk-06)",
"bk07": "prone gluteal sets isometrics (bk-07)",
"bk08": "quadruped leg lift active ROM (bk-08)",
"bk09": "quadruped arm lift active ROM (bk-09)",
"bk10": "quadruped contralateral arm/leg lift active ROM (bk-10)",
"bk11": "prone full back extension active ROM (bk-11)",
"bk12": " propped hip extension alternating active ROM with support (bk-12)",
"bk13": " propped hip extension bilateral  active ROM with support (bk-13)",
"bk14": "quadruped angry cat stretch (bk-14)",
"bk15": "quadruped knee to chest stretch (bk-15)",
"bk16": "supine hooklying trunk rotation active ROM/stretch (bk-16)",
"bk17": "seated low back flexion stretch (bk-17)",
"bk18": "supine single knee to chest self-stretch (bk-18)",
"bk19": "supine double knees to chest self-stretch (bk-19)",
"bk20": "quadruped child pose 'mid-back' stretch (bk-20)",
"bk21": "quadruped mid back side to side stretch in child pose (bk-21)",
"bk22": "supine hooklying posterior pelvic tilt active ROM (bk-22)",
"bk23": "supine curl-up (phase 1) active ROM (bk-23)",
"bk24": "supine diagonal curl-up (phase 1) active ROM (bk-24)",
"bk25": "supine curl-up (phase 2) active ROM (bk-25)",
"bk26": "supine diagonal curl-up (phase 2) active ROM (bk-26)",
"bk27": "supine curl-up (phase 3) active ROM (bk-27)",
"bk28": "supine diagonal curl-up (phase 3) active ROM (bk-28)",
"bk29": "supine partial sit-up for lower abdominals active ROM (bk-29)",
"bk30": "supine lower trunk rotation stretch (bk-30)",
"bk31": "standing wall slides active ROM (bk-31)",
"bk32": "sidelying quadriceps stretch (bk-32)",
"bk33": "seated hamstrings stretch (bk-33)",
"bk34": "supine active hamstrings stretch (bk-34)",
"bk35": "supine lumbar rotation in hooklying gentle active ROM (bk-35)",
"bk36": "sidelying lumbar rotation gentle active ROM (bk-36)",
"bk37": "seated lumbar rotation active ROM (bk-37)",
"bk38": "supine lumbar rotation resisted ROM (bk-38)",
"bk39": "seated trunk rotation resisted ROM (bk-39)",
"bk40": "standing trunk rotation resisted ROM (bk-40)",
"bk41": "standing resisted ROM lumbar diagonal rotation #1 (bk-41)",
"bk42": "standing resisted ROM lumbar diagonal rotation #2 (bk-42)",
"bk43": "seated bilateral scapular retraction resisted ROM ('rows') (bk-43)",
"bk44": "standing back bend active ROM (bk-44)",
"bk45": "seated back extension resisted ROM with elastic (bk-45)",
"bk46": "seated back flexion resisted ROM with elastic (bk-46)",
"bk47": "seated rowing resisted ROM with elastic (long sit) (bk-47)",
"bk48": "standing lifting simulation resisted ROM with elastic (bk-48)",
"bk49": "standing pull activity simulation resisted ROM with elastic (bk-49)",
"bk50": "standing push activity simulation resisted ROM with elastic (bk-50)",
"bk51": "standing back extension resisted ROM with elastic (bk-51)",
"bk52": "seated lumbar rotation resisted ROM with elastic (bk-52)",
"bk53": "seated segmental trunk/back flexion/extension active ROM (bk-53)",
"bk54": "supine piriformis self-stretch (bk-54)",
"bl": "bilateral",
"blar": "both left and right",
"ble": "both lower extremities",
"blscore": "Baseline score is documented for the purposes of goal setting: ***",
"bmpa": "Belle McDougall, PAC",
"bos": "base of support",
"bpne": "BP =  not evaluated , HR = not evaluated (will check at a future appointment)",
"bral": "both right and left",
"bsbf": "Bosu Ball - flat side up",
"bsbr": "Bosu Ball - round side up",
"bue": "both upper extremities",
"cc01": "seated VMO self biofeedback (cc-01)",
"cc02": "standing VMO self biofeedback (cc-02)",
"cc03": "standing step VMO self biofeedback (cc-03)",
"cc04": "standing quad strength: single leg step-up w/ step/stool (cc-04)",
"cc05": "standing proprioception, quad strength, timing, coordination: forward step-up w/ step/stool (cc-05)",
"cc06": "standing proprioception, coordination, quad strength: retro step-up w/ step/stool (cc-06)",
"cc07": "standing quad strength, proprioception: side step-up w/ step/stool (cc-07)",
"cc08": "standing quad strength, proprioception: step over w/ step/stool (cc-08)",
"cc09": "standing coordination, quad strength, proprioception, timing: diagonal step-up w/ step/stool (cc-09)",
"cc10": "standing gluteus medius strength: wall push (cc-10)",
"cc11": "standing quad strength: quarter squat back to wall (cc-11)",
"cc12": "standing quad strength: single leg quarter squats back to wall (cc-12)",
"cc13": "standing quad strength (VMO): quarter squat with external hip rotation (cc-13)",
"cc14": "standing quad strength (VMO): quarter squat with external hip rotation & dumbbells (cc-14)",
"cc15": "standing quad strength: single leg quarter squat with dumbbells (cc-15)",
"cc16": "standing quad strength: quarter squat with elastic (cc-16)",
"cc17": "standing quad strength (VMO): quarter squat external hip rotation with elastic (cc-17)",
"cc18": "standing quad strength, proprioception: quarter squat single leg with elastic (cc-18)",
"cc19": "standing balance proprioception: hip flexion with elastic (cc-19)",
"cc20": "standing balance proprioception: hip extension with elastic (cc-20)",
"cc21": "standing balance proprioception: hip abduction with elastic (cc-21)",
"cc22": "standing balance proprioception: hip adduction with elastic (cc-22)",
"cc23": "standing quad strength: terminal knee extension with elastic (cc-23)",
"cc24": "standing timing, agility: forward walk with elastic (cc-24)",
"cc25": "standing timing, agility: retro walk with elastic (cc-25)",
"cc26": "standing timing, agility: forward run with elastic (cc-26)",
"cc27": "standing timing, agility: retro run with elastic (cc-27)",
"cc28": "standing timing, agility: cross over step with elastic (cc-28)",
"cc29": "standing quad strength: lunge with elastic (cc-29)",
"cc30": "standing quad strength, agility: skier's jump with elastic (cc-30)",
"cc31": "standing quad strength: plyometric jump with elastic from step/stool (cc-31)",
"cc32": "seated range of motion, proprioception: balance board (cc-32)",
"cc33": "standing range of motion, proprioception: balance board - two feet down (cc-33)",
"cc34": "standing range of motion, proprioception: balance board - single limb stance (cc-34)",
"cc35": "standing range of motion, strength, proprioception: balance board with dumbbells (cc-35)",
"cc36": "standing agility, timing, proprioception: side-to-side using fitter (cc-36)",
"cc37": "seated strength, endurance: stationary bike (cc-37)",
"cc38": "standing strength, endurance: stationary bike - standing (cc-38)",
"cc39": "standing strength, endurance: forward stair stepper (cc-39)",
"cc40": "standing strength, endurance: retro stair stepper (cc-40)",
"cc41": "standing strength, endurance: stair stepper with dumbbells (cc-41)",
"cc42": "standing weight bearing, strength: single leg stair stepper (cc-42)",
"cc43": "standing calf strength, endurance: stair stepper - hips (cc-43)",
"cc44": "standing calf strength, endurance: stair stepper - ankles (cc-44)",
"cc45": "standing endurance, agility: forward treadmill (cc-45)",
"cc46": "standing endurance, agility: retro treadmill (cc-46)",
"cc47": "standing agility, timing, proprioception: sideways treadmill (cc-47)",
"cc48": "standing weight bearing: single leg treadmill (cc-48)",
"cc49": "seated hamstring strength: forward stool walk (cc-49)",
"cc50": "seated quad strength: retro stool walk (cc-50)",
"cc51": "seated strength, agility, timing: side stool walk (cc-51)",
"cc52": "standing forward run (cc-52)",
"cc53": "standing retro run (cc-53)",
"cc54": "standing karioka run (cc-54)",
"cc55": "standing side step run (cc-55)",
"cc56": "standing figure eight run (cc-56)",
"cc57": "standing UE: wall shoulder press out (cc-57)",
"cc58": "standing UE: wall push-ups (cc-58)",
"cc59": "standing UE: standing shoulder flexion / extension (cc-59)",
"cc60": "standing UE: standing shoulder motion (cc-60)",
"cc61": "quadruped UE: shoulder flexion / extension (cc-61)",
"cc62": "quadruped UE: shoulder press-up (cc-62)",
"cc63": "quadruped UE: push-up (cc-63)",
"cc64": "quadruped UE: push-up with press-up (cc-64)",
"cc65": " UE: push-up position press-up (cc-65)",
"cc66": " UE: push-ups (cc-66)",
"cc67": " UE: push-up with press-up (cc-67)",
"cc68": "seated UE: press-up (cc-68)",
"cc69": "kneeling UE: fitter side to side (cc-69)",
"cc70": "kneeling UE: fitter diagonal (cc-70)",
"cc71": " UE: fitter push-up position side to side (cc-71)",
"cc72": "kneeling UE: stair climber in knee position (cc-72)",
"cc73": " UE: stair climber push-up position (cc-73)",
"cc74": "kneeling UE: balance board (cc-74)",
"ccw": "clockwise and counter-clockwise",
"cga": "contact guard assistance",
"cht": "Community Health Team",
"ckc": "closed kinetic chain",
"cnt": "Continue with established plan of care.",
"cr3": "cardiac rehabilitation phase 3 or the 'Move to Lose' program",
"cs01": "standing neck rotation active ROM (cs-01)",
"cs02": "standing neck lateral flexion active ROM (cs-02)",
"cs03": "standing neck flexion active ROM  (cs-03)",
"cs04": "standing neck extension active ROM (cs-04)",
"cs05": "standing isometric neck lateral flexion in neutral (cs-05)",
"cs06": "standing isometric neck rotation in neutral (cs-06)",
"cs07": "standing isometric neck flexion in neutral (cs-07)",
"cs08": "standing isometric neck extension in neutral (cs-08)",
"cs09": "standing alternating neck lateral flexion isometrics in neutral (cs-09)",
"cs10": "standing alternating neck rotation isometrics in neutral (cs-10)",
"cs11": "standing alternating neck lateral flexion isometrics out of neutral (cs-11)",
"cs12": "standing unilateral neck lateral flexion isometrics out of neutral (cs-12)",
"cs13": "standing unilateral neck rotation isometrics out of neutral (cs-13)",
"cs14": "standing unilateral neck flexion isometrics out of neutral (cs-14)",
"cs15": "standing unilateral neck extension isometrics out of neutral (cs-15)",
"cs16": "standing neck rotation resisted ROM (cs-16)",
"cs17": "standing neck lateral flexion resisted ROM (cs-17)",
"cs18": "standing neck flexion resisted ROM (cs-18)",
"cs19": "standing neck extension resisted ROM (cs-19)",
"cs20": "standing neck rotation resisted ROM (cs-20)",
"cs21": "standing neck lateral flexion resisted ROM (cs-21)",
"cs22": "standing shoulder shrugs, down and back active ROM (cs-22)",
"cs23": "standing upper trapezius muscle self-stretch (cs-23)",
"cs24": "standing corner/doorway pectoral muscle (chest) stretch 2-3x hold 20-30 sec 2-3x daily (cs-24)",
"cs25": "neck retraction",
"cs26": "seated postero-lateral neck self-stretch (w/ gentle cross body arm traction) (cs-26)",
"cs27": "standing levator scapula self-stretch (cs-27)",
"cs28": "standing upper neck flexion/extension oa nod active ROM (cs-28)",
"cs29": "standing chest and biceps self-stretch (cs-29)",
"cs30": "standing lower neck and upper thoracic self-stretch (cs-30)",
"cs31": "supine neck rotation resisted ROM - outer to mid range (cs-31)",
"cs32": "supine neck rotation resisted ROM - mid to end range (cs-32)",
"cs33": "supine neck lateral flexion resisted ROM - outer to mid range (cs-33)",
"cs34": "supine neck lateral flexion resisted ROM - mid to end range (cs-34)",
"cs35": "sidelying neck flexion resisted ROM - outer to mid range (cs-35)",
"cs36": "sidelying neck flexion resisted ROM - mid to end range (cs-36)",
"cs37": "standing upper neck flexion mobilization active ROM w/ rotation (cs-37)",
"cs38": "standing upper neck rotation mobilization active ROM (cs-38)",
"cs39": "standing upper neck rotation mobilization active ROM w/ lateral flexion (cs-39)",
"cs40": "standing upper neck rotation active ROM (cs-40)",
"cs41": "sidelying neck extension resisted ROM - outer to mid range (cs-41)",
"cs42": "sidelying neck extension resisted ROM - mid to end range (cs-42)",
"cs43": "supine axial extension (with towel roll)",
"cs44": "seated upper neck flexion resisted ROM (cs-44)",
"cs45": "sidelying neck lateral flexion active ROM w/ towel support (cs-45)",
"cs46": "standing neck retraction active ROM with lateral flexion (cs-46)",
"cts": "carpal tunnel syndrome",
"cu00": "Stretch as follows: Repeat each stretch 2-3 repetitions holding 15-30 seconds each, 2-3 x daily. BASIC STRETCHING RULES: 1) Stretch slowly and with control 2) No bouncing 3) No pain 4) Don't compare your flexibility with others 5)The key is to relax 6) Breathing should be slow, rhythmical. Don't hold breath. 7) Hold only stretch tensions that feel good. There are two phases of stretching. PHASE 1 - THE EASY STRETCH: Stretch to where you feel a slight, easy tension. Hold this for 15-30 seconds, and as you do, the tension should diminish. If not, ease off a bit until it feels comfortable. This easy stretch gets the tissues ready for the developmental stretch. PHASE 2 - THE DEVELOPMENTAL STRETCH: After holding the easy stretch, move a fraction of an inch farther into the stretch until you feel the slight tension again. This is the developmental stretch and should be held for 15-30 seconds. This is an excellent way to increase flexibility and get the muscles ready for activity. (cu-00)",
"cu01": "prone dorsal slide - shoulder internal rotation self-stretch (cu-01)",
"cu02": "standing foot on chair dorsiflexion stretch (cu-02)",
"cu03": "seated modified hamstring stretch, long sit (cu-03)",
"cu04": "semi-reclined reverse pendulum I active ROM (cu-04)",
"cu05": "semi-reclined reverse pendulum ll active ROM (cu-05)",
"cu06": "seated self snags, cervical traction active-assisted ROM w/ towel (cu-06)",
"cu07": "seated self snags, cervical rotation active-assisted ROM w/ towel (cu-07)",
"cu08": "standing pendulum exercises passive ROM (cu-08)",
"cu09": "supine shoulder passive ROM flexion (cu-09)",
"cu10": "supine sahrmann 'core' abdominal toning exercise (cu-10)",
"cu11": "sidelying sleeper stretch for shoulder lnternal rotation (cu-11)",
"cu12": "supine thomas position - hip flexor stretch (cu-12)",
"cu13": "seated long arc quads - active ROM (cu-13)",
"cu14": "standing wall gapping active ROM (cu-14)",
"cu15": "sidelying basking seal self-mobilization (on left side) (cu-15)",
"cu16": "sidelying basking seal self-mobilization (on right side) (cu-16)",
"cu17": "sidelying clamshell active ROM (happy clam) (cu-17)",
"cu18": "sidelying hip abduction active ROM (cu-18)",
"cu19": "sidelying hip extension active ROM (cu-19)",
"cu20": "sidelying hip external rotation active ROM (cu-20)",
"cu21": "standing 'monster walk' hip abduction resisted ROM with elastic (cu-21)",
"cu22": "prone knee hamstring curl resisted ROM w/ elastic (cu-22)",
"cu23": "standing shoulder flexion 0-90 degrees resisted ROM w/ elastic (cu-23)",
"cu24": "standing shoulder abduction resisted ROM w/ elastic (cu-24)",
"cu25": "prone plank from knees (beginner) (cu-25)",
"cu26": "prone plank on toes (advanced) (cu-26)",
"cu27": "sidelying plank on elbow (beginner) (cu-27)",
"cu28": "sidelying plank on hand (advanced) (cu-28)",
"cu29": "sidelying shoulder horizontal abduction active ROM (cu-29)",
"cu30": "standing knee ball press, isometric quad sets back to wall (cu-30)",
"cu31": "standing shoulder resisted ROM rowing w/ elastic ('close row') (cu-31)",
"cu32": "standing shoulder external rotation stretch w/ wand at 90 deg abduction (cu-32)",
"cu33": "prone plank/rollouts on physioball (cu-33)",
"cu34": "prone plank on physioball, legs side-to-side (cu-34)",
"cu35": "standing shoulder serratus anterior 'press' active ROM (cu-35)",
"cu36": "quadruped shoulder on hands/knees ('wax on, wax off') active ROM (cu-36)",
"cu37": "standing shoulder wall walking resisted ROM (rubber band hooking as an active rom progression (cu-37)",
"cu38": "standing shoulder horizontal abduction resisted ROM w/ elastic, on wall (cu-38)",
"cu39": "prone twist on physioball active ROM (cu-39)",
"cu40": "supine bridge on physioball active ROM (cu-40)",
"cu41": "prone pike tuck on physioball active ROM (cu-41)",
"cu42": "supine 'V' pass with physioball active ROM (cu-42)",
"cu43": "kneeling abdominal rollout using ball (hamstrings/core) (cu-43)",
"cu44": "supine bridge/hamstring curl over ball active ROM (cu-44)",
"cu45": "standing corner wall stretch (cu-45)",
"cu46": "standing curl and press resisted ROM w/ dumbbells (cu-46)",
"cu47": "standing tennis elbow eccentric wrist extension w/ flexbar resisted ROM (cu-47)",
"cu48": "prone shoulder internal rotation active stretch - dorsal slide (cu-48)",
"cu49": "supine layout pecs stretch, over physioball (cu-49)",
"cu50": " yoga 'downward dog' on one or two leg(s) (cu-50)",
"cu51": "standing off balance squats - heels down side-to-side - holding doorknobs (cu-51)",
"cu52": "prone hip abduction active ROM (cu-52)",
"cu53": "prone knee quadriceps self-stretch (cu-53)",
"cu54": "prone 'Y' shoulder active ROM (cu-54)",
"cu55": "supine shoulder layout thoracic outlet self-stretch (cu-55)",
"cu56": "standing shoulder push-up 'plus' active ROM (cu-56)",
"cu57": "standing shoulder pectoral muscle stretch - in doorway (cu-57)",
"cu58": "standing shoulder external rotation resisted ROM w/ elastic 'no money' (cu-58)",
"cu59": "supine diagonal 1 knee to chest (piriformis) self-stretch (cu-59)",
"cu60": "seated shoulder flexion pulley-assisted active-assisted ROM (cu-60)",
"cu61": "supine sahrmann 'core' abdominal toning exercise 'A' (cu-61)",
"cu62": "seated hip flexion active ROM (march in place) (cu-62)",
"cu63": "seated hip abduction resisted ROM (clamshell) (cu-63)",
"cu64": "seated hip lnternal rotation resisted ROM (cu-64)",
"cu65": "supine bridging active ROM (cu-65)",
"cu66": " see #102 (cu-66)",
"cu67": "seated forearm pronation/supination active ROM with hammer/wrench (cu-67)",
"cu68": "standing median nerve gliding self-stretch - hand on wall (cu-68)",
"cu69": "standing shoulder wall ball active ROM - up/down, left/right, clockwise, and clockwise and counterclockwise (cu-69)",
"cu70": "standing hip isometrics 'squeeze' and 'press' (cu-70)",
"cu71": "supine shoulder flexion active-assisted ROM with wand (cu-71)",
"cu72": "supine shoulder flexion active-assisted ROM (cu-72)",
"cu73": "standing shoulder active-assisted ROM wall walking (cu-73)",
"cu74": "seated marble lift active ROM w/ toes/foot (cu-74)",
"cu75": "seated hip internal rotation resisted ROM w/ elastic (cu-75)",
"cu76": "seated hip external rotation resisted ROM w/ elastic (cu-76)",
"cu77": "standing baps / wobble board - active ROM plantarflexion/dorsiflexion (cu-77)",
"cu78": "standing baps / wobble board - active ROM inversion/eversion (cu-78)",
"cu79": "standing baps board - active ROM in a 360 degree circle clockwise and counterclockwise (cu-79)",
"cu80": "standing shoulder internal rotation stretch w/ pulley - standing (cu-80)",
"cu81": "standing hip abduction active ROM (cu-81)",
"cu82": "standing hip extension active ROM (cu-82)",
"cu83": "standing hip/knee flexion active ROM (march in place) (cu-83)",
"cu84": "standing single leg balance with elastic dangling down from top of a door (cu-84)",
"cu85": "standing serratus anterior resisted ROM ('hug')w/ elastic (cu-85)",
"cu86": "standing triceps resisted ROM w/ elastic (bow and arrow) (cu-86)",
"cu87": "supine physioball pickup resisted ROM w/ lower abdominals/hamstrings (cu-87)",
"cu88": "supine physioball pickup (cu-88)",
"cu89": "standing isometric hip abduction in the closed kinetic chain, pressing into wall (cu-89)",
"cu90": "seated shoulder external rotation self-stretch (cu-90)",
"cu91": "seated isometric hip adduction with pillow (cu-91)",
"cu92": "prone hamstring curl resisted ROM with cuff weight (cu-92)",
"cu93": "seated long arc quads - resisted ROM with cuff weight (cu-93)",
"cu94": "standing hamstring curl resisted ROM with cuff weight (cu-94)",
"cu95": "standing shoulder internal rotation active-assisted ROM behind the back, with wand (cu-95)",
"cu96": "prone neck extension active ROM (cu-96)",
"cu97": "prone shoulder lift off active ROM (cu-97)",
"cu98": "supine shoulder external rotation resisted ROM abducted 90 degrees, with elastic (cu-98)",
"cu99": "standing balance - sway drills / cone of stability (cu-99)",
"cu100": "seated piriformis self-stretch (cu-100)",
"cu101": "standing shoulder abduction resisted ROM with dumbbells - aka chicken wings (cu-101)",
"cu102": "supine shoulder external rotation stretch w/ wand in loose pack position (cu-102)",
"cu103": "supine shoulder external rotation active-assisted ROM - goal post stretch w/ wand (cu-103)",
"cu104": "supine hip abduction active ROM (cu-104)",
"cu105": "seated arch lifts active ROM (cu-105)",
"cu106": "supine over physioball trunk curl active ROM (cu-106)",
"cu107": "seated  Sit to Stand Drill active ROM (cu-107)",
"cu108": "seated 'straight back sit-up' active ROM, using abdominals (cu-108)",
"cvet": "cardiovascular endurance training",
"cwus": "continuous ultrasound",
"daa": "demonstrated and assigned",
"dangle": "Single leg balance drills with elastic (***) dangling down from above for dynamic support ***",
"dbr": "deep breathing relaxation",
"dc": "discontinue",
"dclock1": "diagonal 1 (right foot ahead)",
"dclock2": "diagonal 2 (left foot ahead)",
"dcpt": "Discontinue PT. Thank you for this referral. It has been a pleasure to meet *** and help with *** rehab needs.",
"ddd": "degenerative disc disease",
"demod": "demonstrated and assigned",
"demossm": "demonstrated and assigned - see scanned media",
"df": "dorsiflexion",
"dhs": "Department of Homeland Security",
"djd": "degenerative joint disease",
"dof": "dorsiflexion",
"ds": "degrees",
"ecpa": "Ed Cowey PA-C",
"eer": "externally rotated",
"eft": "Elbow Flexion Test (EFT) Grade *** elicits ***",
"eg": "for example",
"ehs": "Employee Health Service",
"eoec": "eyes open and eyes closed",
"er": "external rotation",
"erir": "external rotation and internal rotation",
"erom": "end ROM",
"etntp": "exquisite tenderness to palpation",
"ettp": "exquisitely tender to palpation",
"evr": "eversion",
"exagg": "exaggerated lumbar lordosis, exaggerated thoracic kyphosis, and forward head posture",
"examso": "examination findings and their relevance to symptoms described as well as the proposed plan of care in physical therapy.",
"faei": "flexion, abduction, external rotation, and internal rotation",
"fes": "functional electrical stimulation",
"fhp": "forward head posture",
"fittest": "Stationary bike 'Fit Test' 5 minutes, seat height: ***, age: ***, weight: *** lb, resistance level: ***, RPE (start): ***/20, HR (start): , Fit Score (estimated VO2 max): ***, Fit Rating: '***', RPE (end) ***/20, HR (end) ***. Taking beta blocker?: ***",
"fttf": "fingertips to floor distance ***&uot;",
"fua": "follow-up appointment",
"ghj": "gleno-humeral joint",
"ghpt": "Gregg M. Horowitz, PT, MS",
"goalsmet": "PT short term and long term goals, aside from those ***, are met.",
"gt": "gait training",
"ha01": "seated finger DIP joint passive ROM (ha-01)",
"ha02": "seated finger PIP joint passive ROM (ha-02)",
"ha03": "seated finger MP joint passive ROM (ha-03)",
"ha04": "seated thumb DIP joint passive ROM (ha-04)",
"ha05": "seated thumb IP joint passive ROM (ha-05)",
"ha06": "seated finger DIP joint active ROM (ha-06)",
"ha07": "seated finger PIP joints active ROM (ha-07)",
"ha08": "seated make a fist active ROM (ha-08)",
"ha09": "seated thumb flexion/extension active ROM (ha-09)",
"ha10": "seated thumb abduction/adduction active ROM (ha-10)",
"ha11": "seated finger opposition active ROM (ha-11)",
"ha12": "seated wrist flexion/extension passive ROM (ha-12)",
"ha13": "seated wrist flexor self-stretch (ha-13)",
"ha14": "seated wrist extensor self-stretch (ha-14)",
"ha15": "seated wrist flexor self-stretch on tabletop (ha-15)",
"ha16": "seated wrist flexor self-stretch palms together (ha-16)",
"ha17": "seated wrist flexion/extension active ROM (ha-17)",
"ha18": "seated forearm pronation/supination active ROM (ha-18)",
"ha19": "seated forearm supination stretch (ha-19)",
"ha20": "seated forearm pronation stretch (ha-20)",
"ha21": "seated wrist isometric flexion (ha-21)",
"ha22": "seated wrist isometric extension (ha-22)",
"ha23": "seated wrist isometric radial deviation (ha-23)",
"ha24": "seated wrist isometric ulnar deviation (ha-24)",
"ha25": "seated forearm isometric pronation (ha-25)",
"ha26": "seated forearm isometric supination (ha-26)",
"ha27": "seated finger resisted ROM flexion (ha-27)",
"ha28": "seated finger resisted ROM extension (ha-28)",
"ha29": "seated wrist flexion resisted ROM w/ elastic (ha-29)",
"ha30": "seated wrist extension resisted ROM w/ elastic (ha-30)",
"ha31": "seated wrist radial deviation resisted ROM w/ elastic (ha-31)",
"ha32": "seated wrist ulnar deviation resisted ROM w/ elastic (ha-32)",
"ha33": "seated forearm pronation resisted ROM w/ elastic (ha-33)",
"ha34": "seated forearm supination resisted ROM w/ elastic (ha-34)",
"ha35": "seated elbow biceps curls resisted ROM w/ elastic (ha-35)",
"ha36": "seated elbow extension resisted ROM w/ elastic (overhead) (ha-36)",
"ha37": "seated forearm pronation/supination resisted ROM w/ dumbbell (ha-37)",
"ha38": "seated elbow flexion/extension passive ROM (ha-38)",
"ha39": "seated elbow flexion/extension active ROM (ha-39)",
"ha40": "seated wrist radial/ulnar deviation passive ROM (ha-40)",
"ha41": "seated wrist radial/ulnar deviation active ROM (ha-41)",
"ha42": "seated wrist radial/ulnar deviation active ROM against gravity (ha-42)",
"ha43": "seated palm hollowing active ROM exercise for thumb, fingers, hand (ha-43)",
"ha44": "seated paper crumpling resisted ROM exercise for thumb and fingers (ha-44)",
"ha45": "seated thumb extension isometrics (ha-45)",
"ha46": "seated thumb flexion isometrics (ha-46)",
"ha47": "seated towel roll squeeze resisted ROM for thumb, fingers, hand (ha-47)",
"ha48": "seated forearm pronation/supination resisted ROM w/ hammer (ha-48)",
"ha49": "seated finger extension, thumb abduction resisted ROM w/ rubberband (ha-49)",
"ha50": "seated finger abduction resisted ROM w/ rubberband (ha-50)",
"ha51": "seated thumb extension resisted ROM w/ rubberband (ha-51)",
"ha52": "seated thumb abduction resisted ROM w/ rubberband (ha-52)",
"ha53": "seated thumb opposition resisted ROM w/ rubberband (ha-53)",
"ha54": "seated finger flexion resisted ROM w/ rubberband (ha-54)",
"ha55": "seated thumb flexion resisted ROM w/ rubberband (ha-55)",
"ha56": "seated finger extension resisted ROM w/ rubberband (ha-56)",
"ha57": "seated elbow extension resisted ROM w/ elastic (low) (ha-57)",
"ha58": "seated elbow flexion/curls resisted ROM w/ elastic (ha-58)",
"hce": "hypercholesterolemia",
"hebenefit": "He should benefit from a course of conservative management in physical therapy to address ***, which affects ***.",
"hep": "home exercise program",
"hepf": "home exercise program finalization",
"hepg": "home exercise program",
"hepp": "home exercise program progression",
"heremains": "He remains appropriate for skilled PT to work toward meeting the goals stated below.",
"hhd": "hand-held dynamometer",
"hk01": "seated self-mobilization: downward knee cap push (hk-01)",
"hk02": "seated self-mobilization: upward knee cap pull (hk-02)",
"hk03": "seated self-mobilization: inward knee cap push (hk-03)",
"hk04": "seated self-mobilization: outward knee cap pull (hk-04)",
"hk05": "supine self-mobilization: posterior glide w/ towel (hk-05)",
"hk06": "seated self-mobilization: knee flexion/extension stretch (hk-06)",
"hk07": "prone self-mobilization: knee extension stretch (hk-07)",
"hk08": "prone self-mobilization: knee flexion active ROM (hk-08)",
"hk09": "hooklying self-mobilization: knee flexion stretch (hk-09)",
"hk10": "kneeling flexion stretch (hk-10)",
"hk11": "seated isometric quadriceps sets (hk-11)",
"hk12": "seated isometric hamstring sets - medial (hk-12)",
"hk13": "seated isometric hamstring sets - lateral (hk-13)",
"hk14": "standing isometric hip flexion w/ pillow (hk-14)",
"hk15": "seated isometric hip abduction w/ pillow (hk-15)",
"hk16": "hooklying isometric hip adduction w/ pillow (hk-16)",
"hk17": "supine straight leg raise phase I active ROM (hk-17)",
"hk18": "hooklying straight leg raise phase II active ROM (hk-18)",
"hk19": "seated straight leg raise phase III active ROM (hk-19)",
"hk20": "prone hip extension active ROM (hk-20)",
"hk21": "sidelying hip abduction active ROM (hk-21)",
"hk22": "sidelying hip adduction active ROM (hk-22)",
"hk23": "supine short arc quads active ROM (hk-23)",
"hk24": "standing knee flexion active ROM (hk-24)",
"hk25": "standing wall slides active ROM (hk-25)",
"hk26": "standing hip adduction resisted ROM w/ elastic (hk-26)",
"hk27": "standing hip abdction resisted ROM w/ elastic (hk-27)",
"hk28": "standing hip extension resisted ROM w/ elastic (hk-28)",
"hk29": "standing hip flexion resisted ROM w/ elastic (hk-29)",
"hk30": "standing hip diagonal resisted ROM w/ elastic (hk-30)",
"hk31": "standing hip diagonal resisted ROM w/ elastic (hk-31)",
"hk32": "seated inner thigh/groin stretch (hk-32)",
"hk33": "supine hamstring stretch heel on wall (hk-33)",
"hk34": "standing hip flexor 'hurdlers' stretch (hk-34)",
"hk35": "seated piriformis stretch (hk-35)",
"hk36": "standing tensor stretch (hk-36)",
"hk37": "standing quadriceps stretch (hk-37)",
"hk38": "supine hamstring stretch (hk-38)",
"hk39": "standing hamstring stretch (hk-39)",
"hk40": "seated hamstring stretch (hk-40)",
"hk41": "standing gastroc stretch hands on wall (hk-41)",
"hk42": "standing soleus stretch hands on wall (hk-42)",
"hk43": "standing terminal knee extension resisted ROM w/ elastic (hk-43)",
"hk44": "seated hamstring curls resisted ROM w/ elastic (hk-44)",
"hk45": "prone hamstring curls resisted ROM w/ elastic (hk-45)",
"hk46": "seated passive ROM knee flexion w/ towel (hk-46)",
"hk47": "supine knee flexion stretch - wall slides (hk-47)",
"hk48": "supine piriformis stretch (hk-48)",
"hk49": "seated isometric quad set in slight flexion w/ towel (hk-49)",
"hk50": "supine hip abduction/adduction active ROM with extended knee (hk-50)",
"hk51": "supine hip abduction/adduction active ROM with knee flexion (hk-51)",
"hk52": "standing lateral step-ups active ROM onto step/stool (hk-52)",
"hk53": "hooklying straight leg raise active ROM with bent knee (hk-53)",
"hk54": "hooklying hip abductor resisted ROM w/ elastic (hk-54)",
"hk55": "seated knee extension resisted ROM w/ elastic (hk-55)",
"hk56": "standing hip hiking active ROM on step/stool (hk-56)",
"hk57": "seated knee flexion resisted ROM w/ elastic (hk-57)",
"hk58": "seated hip external rotation resisted ROM w/ elastic (hk-58)",
"hk59": "seated hip internal rotation resisted ROM w/ elastic (hk-59)",
"hk60": "standing hip flexion active ROM on step/stool (hk-60)",
"hk61": "standing modified hip flexor stretch (hk-61)",
"hk62": "sidelying modified hip abduction active ROM w/ pillow (hk-62)",
"hk63": "seated calf stretch w/ towel (hk-63)",
"hk64": "supine anti-emboli isometric (hk-64)",
"hnp": "disc herniation",
"ho": "history of",
"hold10": "hold for 10 seconds",
"hold15": "hold for 15 seconds",
"hold20": "hold for 20 seconds",
"hold30": "hold for 30 seconds",
"hold1530": "hold for 15 to 30 seconds",
"hold2030": "hold for 20 to 30 seconds",
"hsm": "hamstring muscle",
"htn": "high blood pressure",
"hx": "history",
"hxo": "history of",
"iadl": "instrumental activities of daily living",
"ibs": "irritable bowel syndrome",
"ic": "risks/benefits/alternatives were fully reviewed with the patient and informed consent was obtained before proceeding",
"ifhep": "Independent managing and progressing a sensible home exercise and activity program.",
"iir": "internally rotated",
"indr": "was and remains independent",
"interventions": "{pt treatments:22653:a}",
"inv": "inversion",
"invev": "inversion and eversion",
"iphep": "Independent carrying out preliminary home exercise program with good technique.",
"ir": "internal rotation",
"ism": "infraspinatus muscle",
"itb": "ilio-tibial band",
"lar": "left and right",
"lats": "latissimus dorsi",
"latx": "limb advance time asymmetry",
"lbp": "low back pain",
"lbpt": "land-based physical therapy",
"lefa": "Lower Extremity Functional Assessment",
"lefs": "Lower Extremity Functional Scale",
"lgr": "left greater than right",
"lhd": "left hand dominant",
"lld": "leg length difference",
"lle": "left lower extremity",
"loba": "loss of balance",
"lor": "left or right",
"lpmt": "Lumbar Protective Mechanism Test (LPMT) Grade *** closed kinetic chain loading of the lumbar spine with posterior-directed force and the *** leg in the trailing (lunge) position elicitis ***",
"lrl": "left-right-left",
"lsj": "lumbo-sacral junction",
"lsm": "levator scapula muscle",
"lt": "left",
"ltgabm": "Key applied body mechanics principles are employed, spontaneously, in the course of simulated functional activities.",
"ltggait": "Gait pattern vs. age-matched norms WNL including uneven surfaces and stairs.",
"ltgpain": "Pain is managed to patient satisfaction.",
"ltgsleep": "Able to fall asleep, sleep through the night, and wake in reasonable comfort >= 90% of the time.",
"ltr": "left than right",
"luq": "left upper quarter",
"lvr": "left versus right",
"manrx": "manual therapy",
"mbc": "MindBody Medicine Clinic Management of Chronic Pain Program at UVM. This intensive 13 week group program (requires commitment to meeting once a week for 90 minutes).",
"mckb51": "McKenzie 'Treat Your Own Back' Chapter 5, #1 - Lying Face Down",
"mckb52": "McKenzie 'Treat Your Own Back' Chapter 5, #2 - Lying Face Down in Extension (prone on elbows)",
"mckb53": "McKenzie 'Treat Your Own Back' Chapter 5, #3 - Extension In Lying (prone press up)",
"mckb54": "McKenzie 'Treat Your Own Back' Chapter 5, #4 - Extension in Standing",
"mckn1234": "McKenzie neck rotation to left and right (one-half inch) superimposed on *** neck extension superimposed on neck retraction ***; 10x, up to 10 times daily (combining exercise *** and *** from Treat Your Own Neck).",
"mfr": "myofascial release",
"mkpa": "Michelle Kearney PA-C",
"mnt": "*** minutes",
"mntr": "monitoring home exercise program adherence/form, adjustments to activities of daily living and instrumental activities of daily living, and changes in symptoms if any; adjusting treatment and home exercise program accordingly",
"mobs": "joint mobilization",
"momaybe": "modalities such as ultrasound or e-stim are a contingency for any future exacerbations of swelling or pain, should they occur.",
"mrpa": "Margaret Russel PAC",
"mva": "motor vehicle accident",
"mvi": "multi-vitamin",
"my105": "105 degrees of knee flexion is typically enough to perform well at rising from chairs/toilets, getting in/out of small cars, going up/down stairs step-over-step, etc.",
"n/e": "not evaluated",
"nb": "normal bilaterally",
"nbos": "narrow base of support",
"ndi": "Neck Disability Index",
"ne": "not evaluated ***",
"nextsession": "Continue PT per plan of care. Next session may include: monitoring home exercise program adherence/form, adjustments to activities of daily living and instrumental activities of daily living, and changes in symptoms if any; adjusting treatment and home exercise program accordingly.",
"ng": "negative",
"nlneuro": "no athetosis, tremor, rigidity, or dystonia",
"nmes": "neuromuscular electrical stimulation",
"nmr": "neuro-muscular reeducation",
"noexercise": "Does not exercise beyond normal daily chores/activities.",
"npn": "no problems noted",
"nsew": "north, south, east, and west",
"nwb": "non weight-bearing",
"nxt": "Next session may include:",
"oa": "osteoarthritis",
"obst": "obstacle course using gym mat (single and double thickness), 1/2 foam roller (to step over 2x), AirEx (to step onto 1x)",
"oem": "original equipment",
"okc": "open kinetic chain",
"oob": "out of bed",
"oppt": "out-patient physical therapy",
"optne": "Not evaluated; not indicated for this patient's diagnosis/reason for this referral.",
"osw": "Modified Low Back Pain Disability Questionnaire",
"otc": "over the counter",
"ow": "otherwise",
"pf": "plantarflexion",
"pfa": "patello-femoral",
"pfdf": "plantarflexion/dorsiflexion",
"pfp": "patello-femoral pain",
"phep": "preliminary home exercise program",
"pkb": "prone knee bending (heel-to-buttocks distance / quads length) ***&quot; right, ***&quot; left",
"plf": "plantarflexion",
"pn": "(* indicates pain)",
"posturehead": "Postural awareness: tall/erect head-on-shoulders posture because 1) this frees the facet joints to promote pain-free active ROM and 2) this gives respite to postural muscles that work overtime to support the head on the shoulders when it's not in balance",
"posturesit": "Postural awareness: sit with a tripod (2 ischial tuberosities and the sacrum) sharing the weight equally. Use a lumbar support of some type if this helps to remind you. When gravity intervenes and you find yourself slouching again in the chair, fix it!",
"pow": "post-op week",
"ppd": "pack(s) per day",
"prn": "as needed",
"prom": "passive ROM",
"ps": "positive",
"psis": "posterior superior iliac spine",
"pt44": "*** PT 44 pended !!! ***",
"pted": "patient education re:",
"ptii": "PowerTrack II handheld dynamometer",
"qd": "Quick DASH",
"qlm": "quadratus lumborum muscle",
"qml": "prone knee bending (quads muscle length) heel to buttocks measure *** inches right, *** inches left",
"qqpain": "pain ranges from *** /10 at best ( *** ) to *** /10 at worst ( *** ), and is rated now *** /10. Qualitatively her pain is ***.",
"ral": "right and left",
"rgl": "right greater than left",
"rhd": "right hand dominant",
"ric": "R.I.C.E.",
"rice": "R.I.C.E.",
"riceadvice": "Apply a compressive ACE bandage. Rest and elevate the affected painful area.  Apply cold compresses intermittently as needed.  As pain recedes, begin normal activities slowly as tolerated.  Call if symptoms persist.",
"rle": "right lower extremity",
"rlr": "right-left-right",
"rol": "right or left",
"romankle": "Ankle ROM &gt;= *** plantarflexion and *** dorsiflexion.",
"romknee": "ROM *** knee >= *** flexion, *** extension",
"romshld": "ROM *** shoulder >= *** flexion, *** abduction, *** external rotation, *** internal rotation",
"rov": "return office visit",
"rr": "reviewed and reinforced",
"rrom": "resisted ROM",
"rt": "right",
"rtc": "rotator cuff",
"rtci": "rotator cuff impingement syndrome",
"rtcti": "rotator cuff tendinitis",
"rtcto": "rotator cuff tendinosis",
"rtl": "right than left",
"rtsport": "my advice about return to sport is let a week go by during which you are essentially pain-free, and then wait another full week",
"rtw": "return to work",
"rubberband": "Rubberband hooking on paperclip at full-length mirror with *** cueing, slowly on/off",
"ruq": "right upper quarter",
"rvl": "right versus left",
"rx": "treatment",
"sadc": "sub-acromial decompression",
"saj": "sub-acromial space",
"sands": "stethoscope and sphygomomanometer",
"sapa": "Susan Anderson PA-C",
"sbc": "strong but comfortable",
"schm": "self-care home management",
"scj": "sterno-clavicular joint",
"seegs": "See goals listed below for a summary of progress.",
"seescan": "see scanned media for details",
"selfcare": "Specifically, *** will benefit from our self-care back program where we cover applied body mechanics instruction, postural imperatives, ergonomics, and targeted stretch/strengthen exercises, with specific attention to core muscle strengthening.",
"sfd ": "- see further data",
"sfd": "- see further data",
"sfom": "serial functional outcomes measures",
"sga": "Shaw Gait Assessment",
"sh01": "standing shoulder flexion active-assisted ROM, with wand (sh-01)",
"sh02": "standing shoulder abduction active-assisted ROM, with wand (sh-02)",
"sh03": "supine shoulder internal/external rotation active-assisted ROM with wand (sh-03)",
"sh04": "standing shoulder internal/external rotation active-assisted ROM with wand (sh-04)",
"sh05": "supine shoulder horizontal adduction/abduction active-assisted ROM with wand (sh-05)",
"sh06": "prone shoulder extension ('I') active-assisted ROM with wand (sh-06)",
"sh07": "seated tabletop shoulder flexion self-stretch (sh-07)",
"sh08": "standing shoulder flexion active-assisted ROM - wall slide (sh-08)",
"sh09": "seated tabletop shoulder abduction self-stretch (sh-09)",
"sh10": "seated tabletop shoulder external rotation self-stretch (sh-10)",
"sh11": "standing tabletop shoulder external rotation self-stretch (sh-11)",
"sh12": "standing shoulder extension self-stretch in closed kinetic chain - hands on counter behind and dip (sh-12)",
"sh13": "seated shoulder self-stretching: caudal glide (sh-13)",
"sh14": "supine shoulder self-stretching: anterior glide (sh-14)",
"sh15": "prone shoulder self-stretching: posterior glide (sh-15)",
"sh16": "seated shoulder self-stretching: inferior glide (sh-16)",
"sh17": "standing shoulder self-stretching: inferior glide (sh-17)",
"sh18": "seated shoulder self-stretching: lateral glide (sh-18)",
"sh19": "seated shoulder self-stretching: posterior/inferior glide (for flexion 0-90) (sh-19)",
"sh20": "seated shoulder self-stretching: inferior glide (for abduction 0-90) (sh-20)",
"sh21": "seated shoulder self-stretching: anterior glide for extension (sh-21)",
"sh22": "standing shoulder self-stretching: inferior glide (for abduction >90) (sh-22)",
"sh23": "standing shoulder self-stretching: posterior/inferior glide (for flexion >90) (sh-23)",
"sh24": "standing shoulder self-stretching: posterior/inferior glide (for flexion >90) (sh-24)",
"sh25": "standing codman's pendulum exercise - side-to-side (sh-25)",
"sh26": "standing codman's pendulum exercise - clockwise and ccw (sh-26)",
"sh27": "standing codman's saw active ROM exercise - protraction/retraction (sh-27)",
"sh28": "standing codman's cross active ROM exercise - side-to-side (sh-28)",
"sh29": "standing shoulder isometric flexion using wall (sh-29)",
"sh30": "standing shoulder isometric flexion using other hand (sh-30)",
"sh31": "standing shoulder isometric extension using wall (sh-31)",
"sh32": "standing shoulder isometric abduction using wall (sh-32)",
"sh33": "standing shoulder isometric abduction other hand (sh-33)",
"sh34": "standing shoulder isometric adduction squeezing pillow to side (sh-34)",
"sh35": "standing shoulder isometric external rotation using other hand (sh-35)",
"sh36": "standing shoulder isometric external rotation using wall (sh-36)",
"sh37": "standing shoulder isomteric internal rotation using wall (sh-37)",
"sh38": "standing shoulder isomteric internal rotation using other hand (sh-38)",
"sh39": "standing shoulder isomteric horizontal abduction using wall (sh-39)",
"sh40": "standing shoulder isomteric horizontal adduction using wall (sh-40)",
"sh41": "standing shoulder flexion resisted ROM with elastic (sh-41)",
"sh42": "standing shoulder abduction resisted ROM with elastic (sh-42)",
"sh43": "standing shoulder resisted ROM external rotation with elastic (sh-43)",
"sh44": "standing shoulder resisted ROM internal rotation with elastic (sh-44)",
"sh45": "standing shoulder extension resisted ROM with elastic (sh-45)",
"sh46": "standing shoulder adduction resisted ROM with elastic (sh-46)",
"sh47": "standing shoulder horizontal abduction resisted ROM with elastic (sh-47)",
"sh48": "standing shoulder horizontal adduction resisted ROM with elastic (sh-48)",
"sh49": "standing shoulder D2 diagonal flexion resisted ROM  (sh-49)",
"sh50": "standing shoulder D1 diagonal flexion resisted ROM  (sh-50)",
"sh51": "standing shoulder D1 diagonal extension resisted ROM  (sh-51)",
"sh52": "standing shoulder D2 diagonal extension resisted ROM  (sh-52)",
"sh53": "standing shoulder functional pattern strengthening: tennis forehand (sh-53)",
"sh54": "standing shoulder functional pattern strengthening: tennis backhand (sh-54)",
"sh55": "standing shoulder functional pattern strengthening: throwing, serving (sh-55)",
"sh56": "supine shoulder laced fingers external rotation w/ scapular retraction (sh-56)",
"sh57": "supine shoulder scapular protraction (serratus press) resisted ROM with dumbbells (sh-57)",
"sh58": "prone shoulder horizontal abduction resisted ROM with dumbbells (sh-58)",
"sh59": "prone shoulder flexion resisted ROM with dumbbells (sh-59)",
"sh60": "prone shoulder scapular retraction resisted ROM with dumbbells (sh-60)",
"sh61": "standing shoulder tabletop stabilization: closed chain (hands) (sh-61)",
"sh62": "standing shoulder tabletop stabilization: closed chain (forearms) (sh-62)",
"sh63": "supine shoulder flexion resisted ROM with dumbbells (sh-63)",
"sh64": "standing shoulder flexion resisted ROM with dumbbells (sh-64)",
"sh65": "prone shoulder extension ('I') resisted ROM with dumbbell (sh-65)",
"sh66": "standing shoulder extension resisted ROM with dumbbell (sh-66)",
"sh67": "standing shoulder abduction resisted ROM with dumbbells (sh-67)",
"sh68": "sidelying shoulder external rotation resisted ROM with dumbbell (sh-68)",
"sh69": "sidelying shoulder internal rotation resisted ROM with dumbbell (sh-69)",
"sh70": "quadruped shoulder rocking (sh-70)",
"sh71": "standing shoulder inferior capsule self-stretch (sh-71)",
"sh72": "standing shoulder posterior capsule self-stretch (sh-72)",
"sh73": "standing shoulder internal rotation self-stretch with towel (sh-73)",
"sh74": "standing shoulder scaption - thumb down (sh-74)",
"sh75": "standing shoulder scaption - thumb up (sh-75)",
"sh76": "prone shoulder horizontal abduction active ROM - 'T's - thumbs up (sh-76)",
"sh77": "prone shoulder horizontal abduction active ROM - 'T's - thumbs down (sh-77)",
"sh78": "seated shoulder external rotation resisted ROM at 90 degrees with elastic (sh-78)",
"sh79": "seated shoulder internal rotation resisted ROM at 90 degrees with elastic (sh-79)",
"sh80": "standing shoulder depression resisted ROM with elastic (sh-80)",
"sh81": "standing shoulder wall pushups (sh-81)",
"sh82": "seated shoulder depression resisted ROM with arm support (sh-82)",
"sh83": "standing shoulder flexion active ROM (sh-83)",
"sh84": "shoulder abduction",
"sh85": "standing shoulder internal/external rotation active ROM, abducted 90 degrees (sh-85)",
"sh86": "standing shoulder internal/external rotation active ROM, flexed 90 degrees (sh-86)",
"sh87": "standing shoulder extension active ROM (sh-87)",
"sh88": "standing shoulder pnf D2 flexion with elastic (sh-88)",
"sh89": "standing shoulder pnf D1 flexion with elastic (sh-89)",
"sh90": "standing shoulder pnf D1 extension with elastic (sh-90)",
"sh91": "standing shoulder pnf D2 extension with elastic (sh-91)",
"sh92": "standing shoulder (bilateral) horizontal abduction resisted ROM with elastic (sh-92)",
"shebenefit": "She should benefit from a course of conservative management in physical therapy to address ***, which affects ***.",
"sheremains": "She remains appropriate for skilled PT to work toward meeting the goals stated below.",
"sij": "sacro-iliac joint",
"sls": "single limb support",
"smc": "Sports Medicine Clinic",
"snd": "secondary to",
"snf": "skilled nursing facility",
"sos": "using a step-over-step pattern",
"spadi": "Shoulder Pain and Disability Index",
"sscw": "The patient presents with signs and symptoms that are consistent with the diagnosis of ***.",
"ssm": "supraspinatus muscle",
"sstbe": "The patient presents with signs and symptoms to be expected at this point following ***.",
"ssws": "self-selected walking speed *** m/sec",
"st": "using a step-to pattern",
"stgabm": "Able to articulate 4 key principles of applied body mechanics as related to day-to-day activities frequently performed.",
"stggait": "Gait pattern vs. age-matched norms >= ***% (speed), ***% (step length), ***% (cadence).",
"stgpain": "Pain rating seldom/never exceeds *** with ***.",
"stgsleep": "Able to fall asleep easily and sleep through the night at least ***% of the time.",
"stjn": "sub-talar joint neutral",
"stm": "short term memory",
"stmb": "soft tissue mobilization",
"stsp": "stethoscope and sphygomomanometer",
"stw": "Steps-to-Wellness",
"stwa": "the oncology rehab program a.k.a. Steps-to-Wellness (STW)",
"swivel": "perambulating swivel rolling walker",
"sx": "symptoms",
"tbb": "blue theraband (level 4)",
"tbd": "to be determined",
"tber": "active ROM pat-own-back flexion plus external rotation to *** right and *** left",
"tbg": "green theraband (level 3)",
"tbir": "active ROM reach-behind-the-back extension plus internal rotation to *** right and *** left",
"tbo": "orange theraband (level 2)",
"tbp": "plum/purple theraband (level 5)",
"tby": "yellow theraband (level 1)",
"tfl": "tensor fascia lata muscle",
"tflitb": "tensor fascia lata and iliotibial band",
"tha": "total hip arthroplasty",
"theract": "therapeutic activities",
"therex": "therapeutic exercise",
"tka": "total knee arthroplasty",
"tm": "time constraints",
"tnd": "This discontinue note will serve as updated communication with the referring provider, detailing objective status of the patient, progress toward therapy goals, and the post-PT plan of care.",
"tndc": "This discontinue note will serve as updated communication with the referring provider, detailing objective status of the patient, progress toward therapy goals, and the discharge plan.",
"tne": "This encounter note contains information the may be interesting and useful to the referring provider, relevant to the patient's progress toward  therapy goals, and the plan of care.",
"tnen": "This encounter note contains information the may be interesting and useful to the referring provider, relevant to the patient's progress toward  therapy goals, and the plan of care.",
"tnie": "This initial note contains the examination findings and physical therapy findings, goals, assessment, and plan of care that will be of interest to the referring provider and others involved in the patient's care.",
"tntp": "tenderness to palpation",
"tos": "thoracic outlet syndrome",
"toto": "tension on/tension off",
"ts01": "prone heel squeeze isometrics (ts-01)",
"ts02": "prone hip internal rotation (ts-02)",
"ts03": "prone hip external rotation (ts-03)",
"ts04": "supine isometric abdominal (ts-04)",
"ts05": "hooklying extremity flexion (ts-05)",
"ts06": "hooklying bent leg lift (ts-06)",
"ts07": "hooklying combination (ts-07)",
"ts08": "hooklying heel walk (ts-08)",
"ts09": "supine bridging (ts-09)",
"ts10": "supine unilateral isometric hip flexion (ts-10)",
"ts11": "supine bilateral isometric hip flexion (ts-11)",
"ts12": "supine straight leg raise (ts-12)",
"ts13": "supine bridging with straight leg raise (ts-13)",
"ts14": "supine double knee lift (ts-14)",
"ts15": "supine advanced straight leg raise (ts-15)",
"ts16": "prone bent knee lift (ts-16)",
"ts17": "prone straight leg raise (ts-17)",
"ts18": "prone opposite arm / leg lift (ts-18)",
"ts19": "quadruped upper extremity extension (ts-19)",
"ts20": "quadruped opposite upper and lower extremity extension (ts-20)",
"ts21": "quadruped forward lean (ts-21)",
"ts22": "kneeling forward lean in half-kneeling (ts-22)",
"ts23": "kneeling backward lean in kneeling (ts-23)",
"ts24": "supine isometric gluteals (ts-24)",
"ts25": "prone neck and back isometric (ts-25)",
"ts26": "supine bilateral leg lowering (ts-26)",
"ts27": "kneeling bilateral arm raise (ts-27)",
"ts28": "kneeling to stand (ts-28)",
"ts29": "supine kneeling to supine (ts-29)",
"ts30": "standing kneeling to standing (ts-30)",
"ts31": "standing sitting to standing (ts-31)",
"ts32": "seated forward lean (ts-32)",
"ts33": "seated forward lean to half-kneeling (ts-33)",
"ts34": "standing forward lunge (ts-34)",
"ts35": "standing sideways lunge (ts-35)",
"tsa": "total shoulder arthroplasty",
"ttp": "tender to palpation",
"tug": "timed up and go test",
"tw": "- tolerated well",
"ulntt": "upper limb nerve tension testing revealed ***",
"upslope": "Supine cervical segmental mobilization upslope (facilitating flexion/rotation) to *** ***",
"utm": "upper trapezium muscle",
"vct": "Vertical Compression Test (VCT) Grade *** elicits ***",
"vmo": "vastus medialis oblique muscle",
"vmoa": "vastus medialis oblique muscle (VMO)",
"vsne": "HR and BP not evaluated (will check at a future appointment)",
"vtang": "Vt Air National Guard",
"wb": "weight-bearing",
"wbat": "weight-bearing as tolerated",
"wbos": "wide base of support",
"wclp": "wheelchair leg press",
"wfl": "within functional limits",
"wicc": "walk-in care clinic",
"wnl": "within normal limits",
"wnlp": "within normal limits when previously tested",
"wowo": "wax-on, wax-off ***",
"wse": "work site evaluation",
"wvpd": "Check out the Winooski Valley Park District (www.wvpd.org) for places in the area where you can get outside for trail walking.",
"www": "world wide web"
}